# Generated by Django 5.2.9 on 2026-02-13 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogOutputModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mode', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='info', editable=False, max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(editable=False, max_length=1024)),
            ],
        ),
    ]
