[project]
name = "rbeesoft"
version = "2.0.8"
description = ""
authors = [
    {name = "Brecheisen", email = "r.brecheisen@maastrichtuniversity.nl"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "rbeesoft", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pyinstaller = "^6.17.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
